baseURL: "https://denizakansoy.github.io/" 
title: Deniz Akansoy
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
      - name: Research
        url: research/
        weight: 1
      - name: Software
        url: software/
        weight: 2
      - name: CV
        url: cv.pdf
        weight: 3

params:
    description: "Deniz Akansoy's personal webpage."
    author: Deniz Akansoy
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","software","cv"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Deniz Akansoy
          subtitle: "I am a PhD student in the [**Astrophysical Fluid Dynamics**](https://www.damtp.cam.ac.uk/research/astro/astrophysics-group/) group at the Department of Applied Mathematics and Theoretical Physics, University of Cambridge. I am particularly interested in protoplanetary discs, and understanding planet-disc interactions. In addition, I created and maintain [**DebrisPy**](https://github.com/DenizAkansoy/debrispy/), an open-source Python package for modeling debris-disc surface density profiles based on eccentricity distributions of particles."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Software
              url: software/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: Email
          url: mailto:da619@cam.ac.uk
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=gotuuAwAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/denizakansoy
        - name: LinkedIn
          url: https://www.linkedin.com/in/denizakansoy
        - name: Twitter
          url: https://x.com/denizakansoy

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Deniz Akansoy"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
